services:
  mongo:
    image: mongo:8.0
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  mongo-express:
    image: mongo-express
    restart: unless-stopped
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/
      ME_CONFIG_BASICAUTH: false

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    command:
      - '--config.file=/etc/prometheus/dev-prom.yaml'
    ports:
       - 9090:9090
    restart: unless-stopped
    volumes:
      - ./../metric/dev:/etc/prometheus

  jaeger:
    image: jaegertracing/all-in-one:1.60
    container_name: jaeger
    environment:
      - COLLECTOR_OTLP_ENABLED=true
    hostname: jaeger
    ports:
      - 16686:16686
    #   - 4317:4317
    #   - 4318:4318
    #   - 14268:14268
    restart: unless-stopped

  post-service:
    depends_on:
      mongo:
        condition: service_started
      jaeger:
        condition: service_started
    image: ${IMAGE}
    container_name: post-service
    environment:
      MONGO_URI: mongodb://root:example@mongo:27017
      OTLP_PROBABILITY: 1
      OTEL_EXPORTER_OTLP_ENDPOINT: http://jaeger:4318
      OTEL_EXPORTER_OTLP_INSECURE: true
      LOG_LEVEL: debug
    ports:
       - 3001:3001
    #   - 3002:3002
    restart: unless-stopped